### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by loneicewolf** [bramses/obsidian-audio-alchemiser#1]
Just wanted to explain my appreciation in a issue of this repo, thanks for making this! It's fascinating `:)` Even if I don't use Obsidian-that-often, I still find Obsidian-related repos like this really interesting to read trough and test!
Wishes! Have a good weekend on you as well `^_^`

_Will._

**Comment by bramses** [comment]
thank you @loneicewolf for the nice words! let me know if it works for you, its a fun little experiment at least! XD
